version: '3.8'

services:
  sglang:
    image: sglang/sglang-runtime:jetson
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - MODEL_PATH=${MODEL_PATH:-/models/gemma3n}
      - PORT=30000
      - HOST=0.0.0.0
      # Jetson-specific optimizations
      - TORCH_COMPILE_DISABLE=1
      - TORCHDYNAMO_DISABLE=1
      - CUDA_VISIBLE_DEVICES=0
    ports:
      - "30000:30000"
    volumes:
      - ./models:/models
      - /tmp:/tmp
    command: >
      python -m sglang.launch_server
      --model-path /models/gemma3n
      --host 0.0.0.0
      --port 30000
      --load-format auto
      --trust-remote-code
      --disable-torch-compile
      --attention-backend eager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - SGLANG_URL=http://sglang:30000
      - MODEL_NAME=gemma3n
      - ENABLE_AUDIO=true
      # Jetson optimizations
      - TORCH_COMPILE_DISABLE=1
      - TORCHDYNAMO_DISABLE=1
    depends_on:
      sglang:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  models: