version: "3.8"

services:
  main_app:
    build:
      context: .
      dockerfile: ./jetson/Dockerfile
    image: main_app
    container_name: main_app
    environment:
      STT_URL: http://stt:8000/transcribe
      VAD_URL: http://vad:8000/vad
      TTS_URL: http://kokoroTTS:8000/speak
      OLLAMA_URL: http://ollama:11434
    network_mode: "host"
    devices:
      - /dev/snd:/dev/snd
    depends_on:
      - stt
      - vad
      - kokoroTTS
      - ollama

  stt:
    image: speaches/faster-whisper:latest
    container_name: stt
    ports:
      - "8000:8000"
    environment:
      MODEL_SIZE: small
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  vad:
    build:
      context: ./vad
      dockerfile: Dockerfile
    container_name: vad
    ports:
      - "8001:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  kokoroTTS:
    image: "ghcr.io/rorysroes/kokoro-tts-fastapi:latest"
    container_name: kokoroTTS
    ports:
      - "8002:8000"
    environment:
      VOICE: en_US/vctk_low#p227
    volumes:
      - kokoro_models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  kokoro_models:
  ollama_data: